arrowParens = 'always'
bracketSameLine = false
bracketSpacing = true
endOfLine = 'lf'
jsxSingleQuote = false
printWidth = 90
quoteProps = 'as-needed'
semi = true
singleQuote = true
tabWidth = 4
trailingComma = 'all'
useTabs = false
